name: 'Update Ingress Stats Chart'

on:
  workflow_dispatch:

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Generate new chart'
        run: |
          python -c "from ingress_tracker import IngressHackTracker; tracker = IngressHackTracker(); tracker.plot_item_chart()"

      - name: 'Commit and push changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add item_chart.png
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "📊 Automatically update stats chart"
            git push
          fi
